name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Execute deploy.sh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: /opt/holoclips/deploy.sh
    - name: Purge Cloudflare Cache
      uses: indiesdev/curl@v1
      with:
        url: 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache' 
        method: 'POST'
        headers: '{ "X-Auth-Key": "${{ secrets.CLOUDFLARE_PURGE_KEY }}", "X-Auth-Email": "${{ secrets.CLOUDFLARE_AUTH_EMAIL }}", "Content-Type": "application/json" }'
        body: '{"files":["https://holodex.net/index.html", "https://holodex.net/service-worker.js"]}'
        timeout: 10000
